branches:
  only:
    - master

jobs:
  include:
    - stage: test
      name: "Application"
      language: node_js
      node_js:
        - "10"
      install:
        - npm install -C ./app
      script:
        - npm test -C ./app
     
    - stage: test
      name: "Documentation Tests"
      language: node_js
      node_js:
        - "10"
      install:
        - npm install
      script:
        - npm run lint:md
        - npm run lint:text


notifications:
  on_success: change
  on_failure: always
