--- 
components: 
  schemas: 
    Building: 
      $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/building.yaml#/Building"
    Categories: 
      $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/openstreetmap.yaml#/Categories"
info: 
  description: ""
  title: Building
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - Building
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://fiware.github.io/tutorials.NGSI-LD/examples/building-keyValues.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://fiware.github.io/tutorials.NGSI-LD/examples/building-normalized.jsonld"
          description: OK
        ? "400"
        : 
          content: 
            application/ld+json: 
              schema: 
                properties: 
                  detail: 
                    type: string
                  title: 
                    type: string
                  type: 
                    format: uri
                    type: string
                required: 
                  - type
                type: object
          description: "Bad request"
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format\n"
    name: ngsi-ld
