openapi: "3.0.0"
info:
  description: ''  
  version: "1.0.0"
  title: "Building"

tags: 
  - name: ngsi-ld
    description: >
      NGSI-LD Linked-data Format
    
paths:
  /ngsi-ld/v1/entities:
    get:
      description: Retrieve a set of entities which matches a specific query from an NGSI-LD system
      tags:
        - ngsi-ld
      parameters:
        - in: query
          name: type
          schema:
            type: string
            enum: [Building]
          required: true
      responses:
        '200':
          description: OK
          content:
            application/ld+json:
              examples:
                normalized:
                  summary: Normalized NGSI-LD
                  value: 
                    - $ref : "https://fiware.github.io/tutorials.NGSI-LD/examples/building-normalized.jsonld"   
                keyvalues:
                  summary: Key-Values Pairs
                  value: 
                    - $ref: "https://fiware.github.io/tutorials.NGSI-LD/examples/building-keyValues.json"

        '400':
          description: Bad request
          content:
            application/ld+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    format: uri
                  title:
                    type: string
                  detail:
                    type: string
                required:
                  - type
                      
components:
  schemas:
    Categories:
      $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/building.yaml#/Categories"
    Building:
      $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/building.yaml#/Building"
