openapi: "3.0.0"
info:
  description: ''  
  version: "1.0.0"
  title: "Building"

tags: 
  - name: ngsi-ld
    description: >
      NGSI-LD Linked-data Format

paths:
  /ngsi-ld/v1/entities:
    get:
      tags:
        - ngsi-ld
      parameters:
        - in: query
          name: type
          schema:
            type: string
            enum: [Building]
          required: true
      responses:
        200:
          description: "NGSI-LD Linked-data Format"
          content:
            application/ld+json:
              examples: 
                foo:
                  summary: Linked Data example
                  value: 
                    - $ref : "https://fiware.github.io/tutorials.NGSI-LD/examples/building-normalized.jsonld"   
                keyvalues:
                  summary: Key-Values Pairs
                  value: 
                    - $ref: "https://fiware.github.io/tutorials.NGSI-LD/examples/building-keyValues.json"
                       
components:
  schemas:
    Categories:
      $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/building.yaml#/Categories"
    Building:
      $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/building.yaml#/Building"
