blank_issues_enabled: true
contact_links:
  - name: NGSI-LD Tutorials Documentation
    url: https://ngsi-ld-tutorials.rtfd.io/
    about: |
      check the documentation before asking help or reporting a bug.
  - name: Community Support
    url: https://stackoverflow.com/questions/ask?tags=fiware-orion+fiware
    about: "Volunteers from the Open Source FIWARE community monitor\n\n the https://stackoverflow.com/questions/tagged/fiware tag\n\nand related tags over on Stack Overflow. For development questions only you can ask questions"
