name: "Test Submodules"
on:
  schedule:
  - cron: "0 8 * * 1"
  workflow_dispatch:

jobs:
  test-modules:
    name: Test Submodules
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false 
        fetch-depth: 0
        submodules: recursive
    - name: Build Images
      run: |
        git submodule foreach './services create' || true
    - name: Run Script
      run: |
        git submodule foreach './services start && ./services stop'
